import { APIOSK_UI_BRIDGE, APIOSK_UI_STYLE, uiResourceMeta } from "./ui-bridge.mjs";

export const APIO_V2_CARD_URI = "ui://apiosk/gateway-v2-card-v1.html";

export const APIO_V2_CARD_META = (() => {
  const meta = uiResourceMeta(
    "Shows Apiosk sources, the selected source and price, approval state, progress, balance, source-backed results and safe JSON details."
  );
  // Published provider avatars live in Apiosk's public storage. Other hosts
  // are intentionally blocked and fall back to a generated initial.
  meta.ui.csp.resourceDomains = ["https://mcp.apiosk.com", "https://api.apiosk.com"];
  meta["openai/widgetCSP"].resource_domains = ["https://mcp.apiosk.com", "https://api.apiosk.com"];
  return meta;
})();

export const APIO_V2_CARD_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>${APIOSK_UI_STYLE}
:root{--apiosk:var(--apiosk-accent);--apiosk-strong:#553cc5;--apiosk-soft:var(--apiosk-accent-wash);--good:#36a577;--bad:#d56071}
@media(prefers-color-scheme:dark){:root{--apiosk-strong:#d2b8ff}}
body{padding:8px}.card{padding:0;overflow:hidden;border-radius:18px;box-shadow:0 18px 45px -38px rgba(72,42,145,.62)}
.shell{padding:15px}.top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.apiosk-wordmark{display:block;width:74px;height:24px}.apiosk-wordmark img{display:block;width:74px;height:24px;object-fit:contain;object-position:left center}.pill{border:1px solid color-mix(in srgb,CanvasText 12%,transparent);border-radius:999px;padding:5px 8px;font-size:10px;line-height:1;opacity:.72;text-transform:capitalize}
.hero{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.hero h2{font-size:18px;margin:0}.hero p{margin:5px 0 0}.amount{text-align:right;white-space:nowrap}.amount b{display:block;font-size:18px;font-weight:600;letter-spacing:-.025em}.amount span{font-size:10px;opacity:.6}
.section{border-top:1px solid color-mix(in srgb,CanvasText 10%,transparent);padding:14px 15px}.section-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.section-title h3{font-size:12px;margin:0}.section-title span{font-size:10px;opacity:.6}
.sources{display:grid;gap:8px}.source{display:grid;grid-template-columns:35px minmax(0,1fr) auto;align-items:center;gap:10px;padding:9px;border:1px solid color-mix(in srgb,CanvasText 10%,transparent);border-radius:12px;background:color-mix(in srgb,CanvasText 2.5%,transparent)}.logo{width:35px;height:35px;border-radius:10px;border:1px solid color-mix(in srgb,CanvasText 10%,transparent);object-fit:cover;background:var(--apiosk-soft)}.fallback{display:grid;place-items:center;color:var(--apiosk);font-weight:600}.source-name{font-size:12px;font-weight:600;letter-spacing:-.018em;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.source-meta{font-size:10px;opacity:.62;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.count{font-size:10px;opacity:.62;white-space:nowrap}
.steps{display:grid;gap:9px}.step{display:grid;grid-template-columns:24px minmax(0,1fr) auto;align-items:start;gap:9px}.step-no{display:grid;place-items:center;width:24px;height:24px;border-radius:8px;background:var(--apiosk-soft);color:var(--apiosk);font-size:10px;font-weight:600}.step-title{font-size:12px;font-weight:600;letter-spacing:-.018em}.step-source{display:flex;align-items:center;gap:5px;font-size:10px;opacity:.7;margin-top:3px}.logo.mini{width:17px;height:17px;border-radius:5px;font-size:8px;flex:0 0 auto}.source-badge{display:flex;align-items:center;gap:6px;font-size:10px;opacity:.75}.state{font-size:9px;border-radius:999px;padding:4px 7px;background:color-mix(in srgb,CanvasText 7%,transparent);text-transform:capitalize}.state.completed{color:var(--good);background:color-mix(in srgb,var(--good) 12%,transparent)}.state.failed{color:var(--bad);background:color-mix(in srgb,var(--bad) 12%,transparent)}.state.running{color:var(--apiosk);background:var(--apiosk-soft)}
.notice{font-size:11px;line-height:1.45;padding:10px 11px;border-radius:11px;background:var(--apiosk-soft)}.notice.error{color:var(--bad);background:color-mix(in srgb,var(--bad) 10%,transparent)}
.balances{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.balance{padding:10px;border-radius:11px;background:color-mix(in srgb,CanvasText 5%,transparent)}.balance span{display:block;font-size:9px;opacity:.6}.balance b{display:block;font-size:14px;font-weight:600;letter-spacing:-.02em;margin-top:3px}
.choice-list{display:flex;flex-wrap:wrap;gap:7px}.choice-list button,.actions button{border:1px solid color-mix(in srgb,CanvasText 12%,transparent);background:color-mix(in srgb,CanvasText 5%,transparent);color:CanvasText;font-size:11px;padding:8px 10px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.actions .primary{border-color:transparent;background:var(--apiosk);color:var(--apiosk-accent-fg)}.actions .quiet{background:transparent}.field{display:flex;gap:8px}.field input{min-width:0;flex:1;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:10px;background:Canvas;color:CanvasText;padding:9px 10px;font:inherit;font-size:12px;outline:none}.field input:focus{border-color:var(--apiosk);box-shadow:0 0 0 3px var(--apiosk-soft)}
.result{font-size:12px;line-height:1.55}.result-grid{display:grid;gap:7px;margin-top:9px}.result-row{display:grid;grid-template-columns:minmax(90px,.38fr) minmax(0,1fr);gap:10px;padding:7px 0;border-bottom:1px solid color-mix(in srgb,CanvasText 8%,transparent)}.result-row:last-child{border:0}.key{font-size:10px;opacity:.62;overflow-wrap:anywhere}.value{font-size:11px;overflow-wrap:anywhere;white-space:pre-wrap}details{margin-top:10px;font-size:10px;opacity:.7}pre{max-height:240px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font:10px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}.typing{display:inline-flex;gap:3px;margin-left:5px;vertical-align:middle}.typing i{display:block;width:4px;height:4px;border-radius:50%;background:currentColor;animation:pulse 1.1s infinite ease-in-out}.typing i:nth-child(2){animation-delay:.16s}.typing i:nth-child(3){animation-delay:.32s}@keyframes pulse{0%,70%,100%{opacity:.25;transform:translateY(0)}35%{opacity:1;transform:translateY(-2px)}}
@media(max-width:480px){.hero{display:block}.amount{text-align:left;margin-top:10px}.source{grid-template-columns:32px minmax(0,1fr)}.source .count{grid-column:2}.balances{grid-template-columns:1fr}.result-row{grid-template-columns:1fr;gap:3px}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style></head><body><main class="card" id="card"><div class="shell">
<div class="top"><picture class="apiosk-wordmark"><source media="(prefers-color-scheme:dark)" srcset="https://mcp.apiosk.com/brand/wordmark-white-320.png"><img src="https://mcp.apiosk.com/brand/wordmark-black-320.png" alt="Apiosk" width="320" height="103"></picture><span class="pill" id="status-pill">Loading</span></div>
<div class="hero"><div><h2 id="title">Preparing your request</h2><p id="subtitle" class="meta">Connecting to Apiosk<span class="typing"><i></i><i></i><i></i></span></p></div><div class="amount hidden" id="price"><b id="price-value"></b><span>maximum total</span></div></div>
</div><div id="sections"></div><div class="section hidden" id="feedback"><div id="feedback-text" class="notice" role="status" aria-live="polite"></div></div></main>
<script>${APIOSK_UI_BRIDGE}</script><script>
const byId=id=>document.getElementById(id),sections=byId('sections'),feedback=byId('feedback'),feedbackText=byId('feedback-text');let output=null,input={},busy=false;
const text=v=>v==null?'':String(v),pretty=v=>text(v).replace(/[._-]+/g,' ').replace(/\\b\\w/g,c=>c.toUpperCase());
function el(tag,className,value){const n=document.createElement(tag);if(className)n.className=className;if(value!=null)n.textContent=text(value);return n}
function money(atomic,currency='USDC'){if(atomic==null||!/^-?\\d+$/.test(text(atomic)))return null;const n=BigInt(text(atomic)),neg=n<0n,a=neg?-n:n;return(neg?'-':'')+(a/1000000n)+'.'+(a%1000000n).toString().padStart(6,'0').replace(/0+$/,'').padEnd(2,'0')+' '+currency}
function section(title,aside){const s=el('section','section'),h=el('div','section-title'),t=el('h3','',title);h.append(t);if(aside)h.append(aside&&aside.nodeType?aside:el('span','',aside));s.append(h);sections.append(s);return s}
function showFeedback(message,kind=''){feedback.classList.remove('hidden');feedbackText.textContent=message;feedbackText.className='notice '+kind;window.apiosk.resize()}
function safeLogo(url){try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='api.apiosk.com'?u.href:null}catch{return null}}
function sourceLogo(source){const url=safeLogo(source&&source.logo_url);if(url){const img=el('img','logo');img.alt='';img.src=url;img.onerror=()=>img.replaceWith(fallbackLogo(source));return img}return fallbackLogo(source)}
function fallbackLogo(source){return el('span','logo fallback',text(source&&source.name||'A').trim().slice(0,1).toUpperCase()||'A')}
function invokeLabel(status){return({ready:'Ready',needs_input:'Input needed',needs_selection:'Choose one',requires_approval:'Approval needed',running:'Running',succeeded:'Completed',partial:'Partial result',unsupported:'Unavailable',state_conflict:'Updated',failed:'Failed'}[status]||pretty(status||'Ready'))}
function toolArgs(action,value){const args={action_id:action.action_id,state:output.state,idempotency_key:action.action_id,quote_ref:output.proposal&&output.proposal.quote_ref||null,input:value==null?null:value};return args}
async function callAction(action,value){if(busy||!output||!output.state)return;busy=true;showFeedback(action.label||'Updating…');try{const next=await window.apiosk.callTool('apiosk_execute',toolArgs(action,value));render(next)}catch(e){showFeedback(e&&e.message||'The request could not be completed.','error')}finally{busy=false}}
function actionButton(action,label,primary=false,value=null){const b=el('button',primary?'primary':'',label||action.label);b.type='button';b.onclick=()=>callAction(action,value);return b}
function renderSources(data){const rows=Array.isArray(data.sources)?data.sources:[];byId('title').textContent=data.total===1?'1 matching source':text(data.total||rows.length)+' matching sources';byId('subtitle').textContent='Explore verified capabilities before asking a data question.';const s=section('Sources',text(data.offset||0)+'–'+text((data.offset||0)+rows.length)+' of '+text(data.total||rows.length)),list=el('div','sources');for(const source of rows.slice(0,12)){const row=el('div','source'),copy=el('div'),name=el('div','source-name',source.name||source.slug),meta=el('div','source-meta',[source.category,...(source.capabilities||[]).slice(0,2)].filter(Boolean).map(pretty).join(' · '));copy.append(name,meta);row.append(sourceLogo(source),copy,el('span','count',text(source.endpoint_count||0)+' endpoints'));list.append(row)}s.append(list);const actions=el('div','actions');if(Number.isInteger(data.next_offset)){const b=el('button','quiet','Next page');b.onclick=async()=>{if(busy)return;busy=true;showFeedback('Loading the next sources…');try{const args={...input,offset:data.next_offset,limit:input.limit||20};render(await window.apiosk.callTool('apiosk_sources',args))}catch(e){showFeedback(e&&e.message||'Could not load the next page.','error')}finally{busy=false}};actions.append(b)}if(actions.childNodes.length)s.append(actions)}
function sourceLine(source){const line=el('div','step-source'),logo=sourceLogo(source);logo.classList.add('mini');line.append(logo,el('span','',source.name||source.provider||'Apiosk source'));return line}
function sourceBadge(source){const badge=el('div','source-badge'),logo=sourceLogo(source);logo.classList.add('mini');badge.append(logo,el('span','',source.name||source.provider||'Source'));return badge}
function renderPlan(data){const p=data.proposal;if(!p)return;byId('title').textContent=p.label||'Your data plan';byId('subtitle').textContent='Review the source and total before anything runs.';const formatted=money(p.max_total_atomic,p.currency);if(formatted){byId('price').classList.remove('hidden');byId('price-value').textContent=formatted}const s=section('Plan',text((p.steps||[]).length)+' '+((p.steps||[]).length===1?'step':'steps')),list=el('div','steps');(p.steps||[]).forEach((step,i)=>{const d=(p.step_details||[])[i]||{},row=el('div','step'),copy=el('div'),source=d.source||{};copy.append(el('div','step-title',d.title||pretty(step)),sourceLine(source));row.append(el('span','step-no',i+1),copy,el('span','state '+text(d.status||'pending'),d.status||'pending'));list.append(row)});s.append(list)}
function renderChoices(data){const select=(data.next_actions||[]).find(a=>a.kind==='select_entity'),candidates=data.context_view&&data.context_view.candidates;if(!select||!Array.isArray(candidates)||!candidates.length)return;const s=section('Choose the right match','No identifiers required'),list=el('div','choice-list');for(const c of candidates){const b=el('button','',c.label);b.onclick=()=>callAction(select,{entity_ref:c.entity_ref});list.append(b)}s.append(list)}
function renderInput(data){const action=(data.next_actions||[]).find(a=>a.kind==='supply_input');if(!action)return;const s=section(action.label||'One detail is needed'),form=el('form','field'),field=el('input');field.required=true;field.autocomplete='off';field.placeholder='Enter the requested value';const b=el('button','primary','Continue');form.append(field,b);form.onsubmit=e=>{e.preventDefault();let value=field.value.trim();const type=action.input_schema&&action.input_schema.properties&&action.input_schema.properties.value&&action.input_schema.properties.value.type;if(type==='integer'||type==='number')value=Number(value);else if(type==='boolean')value=value==='true';callAction(action,{value})};s.append(form)}
function renderBilling(data){const b=data.billing;if(!b)return;const available=money(b.balance_available,b.currency),charged=money(b.total_charged,b.currency);if(available==null&&charged==null)return;const s=section('Apiosk balance',b.authorization_active?'Approved for this quote':'Protected by your limits'),grid=el('div','balances');if(charged!=null){const box=el('div','balance');box.append(el('span','',Number(b.total_charged)>0?'Charged':'Charged so far'),el('b','',charged));grid.append(box)}if(available!=null){const box=el('div','balance');box.append(el('span','','Available'),el('b','',available));grid.append(box)}s.append(grid)}
function scalarRows(value,depth=0){if(depth>1||value==null)return[];if(Array.isArray(value))return value.slice(0,8).map((v,i)=>[i+1,typeof v==='object'?JSON.stringify(v):v]);if(typeof value!=='object')return[['Result',value]];return Object.entries(value).filter(([k])=>!['raw','items','data'].includes(k)).slice(0,14).map(([k,v])=>[pretty(k),typeof v==='object'?JSON.stringify(v):v])}
function renderResult(data){if(data.result==null)return;byId('title').textContent=data.status==='partial'?'Partial source result':'Source result';byId('subtitle').textContent='Returned by the selected source and ready for your assistant.';const source=data.result&&data.result.source||{},s=section('Result',sourceBadge(source)),wrap=el('div','result'),grid=el('div','result-grid');let body=data.result&&data.result.data!=null?data.result.data:data.result;const rows=scalarRows(body);for(const [k,v] of rows){const row=el('div','result-row');row.append(el('div','key',k),el('div','value',v));grid.append(row)}if(rows.length)wrap.append(grid);else wrap.append(el('div','notice','The source returned structured data. Open the JSON details below.'));const details=el('details'),summary=el('summary','','Source JSON'),pre=el('pre','',JSON.stringify(data.result,null,2));details.append(summary,pre);wrap.append(details);s.append(wrap)}
function renderActions(data){const actions=data.next_actions||[],run=actions.find(a=>a.kind==='execute_quoted_step'),poll=actions.find(a=>a.kind==='poll'),read=actions.filter(a=>a.kind==='read_result'),cancel=actions.find(a=>a.kind==='cancel');if(!run&&!poll&&!read.length&&!cancel)return;const s=section('Next step'),wrap=el('div','actions'),approved=data.billing&&data.billing.authorization_active&&data.billing.quote_ref===(data.proposal&&data.proposal.quote_ref);if(run&&!approved&&data.proposal&&data.proposal.approval_url){const b=el('button','primary','Review and approve');b.onclick=async()=>{const opened=await window.apiosk.openLink(data.proposal.approval_url);showFeedback(opened?'Approval opened in Apiosk. Return here after approving.':'Open Apiosk to approve this request.',opened?'':'error')};wrap.append(b);if(data.state&&data.state.state_ref){const refresh=el('button','quiet','Refresh approval');refresh.onclick=async()=>{if(busy)return;busy=true;showFeedback('Checking your approval…');try{render(await window.apiosk.callTool('apiosk_execute',{recover_task_ref:data.state.state_ref}))}catch(e){showFeedback(e&&e.message||'Could not refresh this request.','error')}finally{busy=false}};wrap.append(refresh)}}else if(run&&approved)wrap.append(actionButton(run,'Run approved source',true));if(poll)wrap.append(actionButton(poll,'Check progress'));for(const a of read.slice(0,2))wrap.append(actionButton(a,a.label||'View result'));if(cancel)wrap.append(actionButton(cancel,'Cancel'));s.append(wrap)}
function renderErrors(data){const errors=Array.isArray(data.errors)?data.errors:[];if(!errors.length)return;const s=section('Needs attention');for(const e of errors)s.append(el('div','notice error',e.message||e.code||'The request could not be completed.'))}
function render(data){if(!data||typeof data!=='object')return;output=data;sections.replaceChildren();feedback.classList.add('hidden');byId('price').classList.add('hidden');const status=Array.isArray(data.sources)?'ready':data.status||'ready';byId('status-pill').textContent=invokeLabel(status);if(Array.isArray(data.sources))renderSources(data);else{byId('title').textContent=invokeLabel(data.status);byId('subtitle').textContent=data.status==='running'?'The selected source is working on your request.':'Your Apiosk request is up to date.';renderPlan(data);renderChoices(data);renderInput(data);renderResult(data);renderBilling(data);renderActions(data);renderErrors(data)}window.apiosk.resize()}
window.apiosk.onInput&&window.apiosk.onInput(value=>{input=value||{}});window.apiosk.onData(render);
</script></body></html>`;
