export const APIO_OFFER_CARD_URI = "ui://apiosk/offer-card.html";

export const APIO_OFFER_CARD_META = {
  ui: {
    prefersBorder: true,
    domain: "https://mcp.apiosk.com",
    csp: { connectDomains: [], resourceDomains: [] },
  },
  "openai/widgetCSP": { connect_domains: [], resource_domains: [] },
  "openai/widgetDomain": "https://mcp.apiosk.com",
  "openai/widgetPrefersBorder": true,
  "openai/widgetDescription":
    "Shows Apiosk's top provider, exact per-call price, required inputs, and explicit Approve and Deny actions.",
};

// Self-contained and dependency-free so every MCP Apps host can render the
// decision without fetching scripts, styles, fonts or provider-controlled data.
export const APIO_OFFER_CARD_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
:root{color-scheme:light dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;padding:12px;background:transparent;color:CanvasText}.card{border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:16px;padding:16px;background:color-mix(in srgb,Canvas 96%,transparent)}.eyebrow{font-size:11px;letter-spacing:.08em;text-transform:uppercase;opacity:.58}.row{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-top:6px}h2{font-size:18px;line-height:1.25;margin:0}.price{font-weight:750;font-size:18px;white-space:nowrap}.meta,.description,.status{font-size:12px;line-height:1.45;opacity:.72}.description{margin:10px 0 0}.fields{display:grid;gap:10px;margin-top:14px}.field{display:grid;gap:5px}.field label{font-size:12px;font-weight:650}.required{color:#b94848}input,select{width:100%;padding:9px 10px;border-radius:9px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);background:Canvas;color:CanvasText;font:inherit}.actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px}button{border:0;border-radius:10px;padding:10px 12px;font:inherit;font-weight:700;cursor:pointer}.approve{background:#167a50;color:white}.deny{background:color-mix(in srgb,CanvasText 9%,transparent);color:CanvasText}.approve:disabled,.deny:disabled{opacity:.5;cursor:default}.status{margin-top:12px;min-height:18px}.status.error{color:#b94848;opacity:1}.status.ok{color:#167a50;opacity:1}.hidden{display:none}.link{display:inline-block;margin-top:8px;color:inherit}
</style></head>
<body><main class="card"><div class="eyebrow">Top provider</div><div class="row"><div><h2 id="provider">Apiosk</h2><div id="meta" class="meta"></div></div><div id="price" class="price"></div></div><p id="description" class="description"></p><form id="fields" class="fields"></form><div id="actions" class="actions"><button id="approve" class="approve" type="button">Approve</button><button id="deny" class="deny" type="button">Deny</button></div><div id="status" class="status" role="status" aria-live="polite"></div></main>
<script>
const byId=id=>document.getElementById(id), provider=byId('provider'),meta=byId('meta'),price=byId('price'),description=byId('description'),fields=byId('fields'),approve=byId('approve'),deny=byId('deny'),status=byId('status');
let output=null,top=null,busy=false;
const money=v=>typeof v==='number'&&Number.isFinite(v)?'$'+v.toFixed(6).replace(/0+$/,'').replace(/\.$/,''):'Price unavailable';
function toolOutput(){return window.openai?.toolOutput??window.openai?.structuredContent??null}
function setStatus(text,kind=''){status.textContent=text||'';status.className='status '+kind}
function fieldValue(control,type){if(type==='boolean')return control.checked;const raw=control.value;if(type==='integer')return raw===''?undefined:Math.trunc(Number(raw));if(type==='number')return raw===''?undefined:Number(raw);return raw}
function drawField(field){const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('label');label.htmlFor='input-'+field.name;label.textContent=field.label||field.name;if(field.required){const star=document.createElement('span');star.className='required';star.textContent=' *';label.append(star)}let control;if(Array.isArray(field.options)&&field.options.length){control=document.createElement('select');const blank=document.createElement('option');blank.value='';blank.textContent='Choose…';control.append(blank,...field.options.map(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;return option}))}else{control=document.createElement('input');control.type=field.type==='boolean'?'checkbox':(['integer','number'].includes(field.type)?'number':'text');if(field.type==='integer')control.step='1'}control.id='input-'+field.name;control.dataset.name=field.name;control.dataset.location=field.location||'body';control.dataset.valueType=field.type||'string';control.dataset.required=field.required?'true':'false';if(field.default_value!==undefined){if(field.type==='boolean')control.checked=Boolean(field.default_value);else control.value=String(field.default_value)}if(field.description){const hint=document.createElement('div');hint.className='meta';hint.textContent=field.description;wrap.append(label,control,hint)}else wrap.append(label,control);return wrap}
function render(value){output=value&&typeof value==='object'?value:null;top=output?.top||null;if(!top){provider.textContent='No matching provider';meta.textContent='';price.textContent='';description.textContent=output?.message||'Try restating the job.';fields.replaceChildren();approve.disabled=true;deny.textContent='Close';return}provider.textContent=top.provider||'Unknown provider';price.textContent=money(top.price_usdc);meta.textContent=[top.source,top.relevance==null?null:top.relevance+'/100 relevance'].filter(Boolean).join(' · ');description.textContent=top.description||'';fields.replaceChildren(...(top.input_fields||[]).map(drawField));approve.textContent=output?.approval?.approve_label||'Approve · '+money(top.price_usdc);deny.textContent=output?.approval?.deny_label||'Deny';approve.disabled=false;deny.disabled=false;setStatus('Nothing is spent until you approve.');}
function args(){const flat={},parts={path:{},query:{},body:{}};for(const control of fields.querySelectorAll('input,select')){const value=fieldValue(control,control.dataset.valueType);if((value===undefined||value==='')&&control.dataset.required==='true')throw new Error('Fill in '+control.closest('.field').querySelector('label').textContent.replace(' *','')+'.');if(value===undefined||value==='')continue;flat[control.dataset.name]=value;parts[control.dataset.location][control.dataset.name]=value}return{offer_token:top.offer_token,prompt:output.query,max_price_usdc:top.price_usdc,input:flat,query:parts.query,path_params:parts.path,input_parts:parts}}
function structured(result){if(result?.structuredContent)return result.structuredContent;if(result?.content?.[0]?.text){try{return JSON.parse(result.content[0].text)}catch{}}return result}
approve.addEventListener('click',async()=>{if(!top||busy)return;let callArgs;try{callArgs=args()}catch(error){setStatus(error.message,'error');return}busy=true;approve.disabled=true;deny.disabled=true;setStatus('Running '+(top.provider||'provider')+'…');try{if(window.openai?.callTool){const result=structured(await window.openai.callTool('apiosk_execute',callArgs));if(result?.status==='approval_required'){setStatus(result.message||'This purchase is waiting for approval.','error');if(result.approve_url&&window.openai?.openExternal){const link=document.createElement('button');link.type='button';link.className='approve link';link.textContent='Open approval';link.onclick=()=>window.openai.openExternal({href:result.approve_url});status.append(document.createElement('br'),link)}}else if(result?.status==='payment_required'||result?.status==='not_authorised'){setStatus(result.message||'This call could not be paid.','error')}else if(result?.status==='ok'||result?.ok===true){setStatus('Approved and completed. The result is in the conversation.','ok');if(window.openai?.sendFollowUpMessage)await window.openai.sendFollowUpMessage({prompt:'Summarise the completed Apiosk result and answer my original question. Include the charged price briefly.',scrollToBottom:true})}else setStatus(result?.message||'The call returned without a result.','error')}else if(window.openai?.sendFollowUpMessage){await window.openai.sendFollowUpMessage({prompt:'I approve '+(top.provider||'this provider')+' at '+money(top.price_usdc)+'. Run apiosk_execute using the offer and required values from this Apiosk card, then answer my original question.',scrollToBottom:true});setStatus('Approval sent.','ok')}else setStatus('Approval is unavailable in this client. Say “approve” in the conversation.','error')}catch(error){setStatus(error?.message||'The approved call failed.','error')}finally{busy=false;if(!status.classList.contains('ok')){approve.disabled=false;deny.disabled=false}}});
deny.addEventListener('click',async()=>{if(busy)return;approve.disabled=true;deny.disabled=true;setStatus('Denied. Nothing was spent.','ok');window.openai?.setWidgetState?.({decision:'denied',offer_token:top?.offer_token||null});if(window.openai?.sendFollowUpMessage)await window.openai.sendFollowUpMessage({prompt:'I deny the proposed Apiosk purchase. Do not execute it and do not spend anything.',scrollToBottom:false})});
render(toolOutput());window.addEventListener('openai:set_globals',event=>render(event.detail?.globals?.toolOutput??event.detail?.toolOutput));
</script></body></html>`;
