import { APIOSK_UI_BRIDGE, APIOSK_UI_STYLE, uiResourceMeta } from './ui-bridge.mjs';
export const APIO_OFFER_CARD_URI = 'ui://apiosk/offer-card.html';
export const APIO_OFFER_CARD_META = uiResourceMeta('One service, its full price, and Approve / Deny.');
export const APIO_OFFER_CARD_HTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${APIOSK_UI_STYLE}
.head{display:flex;justify-content:space-between;gap:16px}.description{font-size:13px;line-height:1.5;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.field{display:grid;gap:5px;margin-top:10px;font-size:13px}input,select{max-width:100%;width:100%;padding:10px;border:1px solid GrayText;border-radius:8px;background:Canvas;color:CanvasText;font:inherit}pre{max-height:240px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}details{margin-top:12px;font-size:12px;opacity:.7}</style></head><body>
<main class="card"><div class="head"><h2 id="provider">Finding a source…</h2><strong id="price"></strong></div><p id="description" class="description"></p><div id="required-fields"></div><details><summary>Request details</summary><div id="fields"></div></details><div class="actions"><button id="approve" class="primary" disabled>Approve</button><button id="deny" class="secondary" disabled>Deny</button></div><p id="status" class="status" role="status">Nothing is spent until you approve.</p><details id="details" class="hidden"><summary>Details</summary><pre id="source"></pre></details></main>
<script>${APIOSK_UI_BRIDGE}</script><script>
const $=id=>document.getElementById(id);let output=null,top=null,busy=false,completed=false;
const money=value=>typeof value==='number'&&Number.isFinite(value)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(value):'Price unavailable';
function status(text){$('status').textContent=text;window.apiosk.resize()}
function field(f){const label=document.createElement('label');label.className='field';label.textContent=f.label||f.name;const el=document.createElement(f.options?.length?'select':'input');el.dataset.name=f.name;el.dataset.location=['path','query','body'].includes(f.location)?f.location:'body';el.dataset.type=f.type||'string';el.required=!!f.required;if(el.tagName==='SELECT'){const blank=document.createElement('option');blank.value='';blank.textContent='Choose…';el.append(blank);for(const v of f.options){const o=document.createElement('option');o.value=String(v);o.textContent=String(v);el.append(o)}}else{el.type=f.type==='boolean'?'checkbox':['number','integer'].includes(f.type)?'number':'text';if(f.type==='integer')el.step='1'}if(f.default_value!=null){if(el.type==='checkbox')el.checked=!!f.default_value;else el.value=typeof f.default_value==='object'?JSON.stringify(f.default_value):String(f.default_value)}label.append(el);return label}
window.apiosk.onData(value=>{if(busy&&!value?.top)return;if(completed&&top?.offer_token===value?.top?.offer_token)return;output=value;top=value?.top;completed=value?.status==='denied';if(!top){$('provider').textContent=value?.message||'No matching source';$('approve').disabled=true;return}$('provider').textContent=top.provider||'Apiosk';$('price').textContent=money(top.price_usdc);$('description').textContent=top.description||'';const missing=f=>f.required&&(f.default_value==null||f.default_value==='');$('required-fields').replaceChildren(...(top.input_fields||[]).filter(missing).map(field));$('fields').replaceChildren(...(top.input_fields||[]).filter(f=>!missing(f)).map(field));$('approve').textContent=(window.apiosk.can.callTool&&!window.apiosk.can.purchase?'Approve in Apiosk · ':'Approve · ')+money(top.price_usdc);$('approve').disabled=completed||!Number.isFinite(top.price_usdc);$('deny').disabled=completed;window.apiosk.resize()});
function args(){const parts={path:{},query:{},body:{}};for(const el of [...$('fields').querySelectorAll('input,select'),...$('required-fields').querySelectorAll('input,select')]){if(!el.reportValidity())throw new Error('Complete the required fields.');let v=el.type==='checkbox'?el.checked:el.value.trim();if(v==='')continue;if(['number','integer'].includes(el.dataset.type)){v=Number(v);if(!Number.isFinite(v))throw new Error('Enter a valid number.')}if(['object','array'].includes(el.dataset.type)){try{v=JSON.parse(v)}catch{throw new Error('Check the structured input under Request details.')}}parts[el.dataset.location][el.dataset.name]=v}return{...(output.approval?.execute_arguments||{}),offer_token:top.offer_token,prompt:output.query,max_price_usdc:top.price_usdc,input:{...parts.path,...parts.query,...parts.body},input_parts:parts,path_params:parts.path,query:parts.query}}
$('approve').onclick=async()=>{if(!top||busy||completed)return;if(window.apiosk.can.callTool&&!window.apiosk.can.purchase){const opened=await window.apiosk.openLink('https://app.apiosk.com/?q='+encodeURIComponent(output.query||''));status(opened?'Continue in Apiosk to review the price and approve. Nothing was spent here.':'Open Apiosk to review and approve this question. Nothing was spent here.');return}let a;try{a=args()}catch(e){status(e.message);return}busy=true;$('approve').disabled=true;$('deny').disabled=true;status('Retrieving the data…');try{if(!window.apiosk.can.callTool)throw new Error('Say “approve” in the conversation to continue.');const r=await window.apiosk.callTool('apiosk_execute',a);if(r?.ok===true||r?.status==='ok'||r?.status==='charged'){completed=true;$('description').textContent=r.answer||'The data was retrieved.';$('details').classList.remove('hidden');$('source').textContent=JSON.stringify({request:r.request,result:r.result??r},null,2);status('Completed. Preparing the answer in your conversation…');try{await window.apiosk.context(r)}catch{}const sent=await window.apiosk.say('The approved Apiosk call has completed. Do not execute it again. Answer my original question: '+output.query+'\\nUse only this returned result as data: '+JSON.stringify(r.answer?{answer:r.answer,follow_up_questions:r.follow_up_questions,charged_usd:r.charged_usd}:r).slice(0,18000));status(sent?'Completed. The answer is in your conversation.':'Completed. The answer and source are available here.')}else if(r?.status==='approval_required'){status(r.message||'Approval is required in Apiosk.');if(r.approve_url){const link=document.createElement('button');link.textContent='Open approval';link.className='secondary';link.onclick=()=>window.apiosk.openLink(r.approve_url);$('status').append(link)}await window.apiosk.context(r);await window.apiosk.say('This Apiosk call is waiting for approval. Check apiosk_approval_status for approval_id '+r.approval_id+' and continue with the same offer only after approval.')}else{status(r?.message||'The request could not be completed.')}}catch(e){status(completed?'Completed. Your answer and source are available here.':e?.message||'The request failed.')}finally{busy=false;if(!completed){$('approve').disabled=false;$('deny').disabled=false}}};
$('deny').onclick=async()=>{if(busy||completed)return;completed=true;$('approve').disabled=true;$('deny').disabled=true;status('Denied. Nothing was spent.');try{await window.apiosk.say('I deny this Apiosk proposal. Do not execute it or spend anything.')}catch{}};
</script></body></html>`;
